package com.vitasync.management;

import com.vitasync.model.PatientRecord;
import com.vitasync.model.VitalSignReading;
import com.zaxxer.hikari.HikariDataSource;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.sql.*;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;

/**
 * Generates a discharge summary for a patient based on their vital sign history.
 * Computes: avg HR, avg SpO2, peak critical events, assigned doctor, duration.
 */
public class DischargeSummaryService {

    private static final Logger log = LoggerFactory.getLogger(DischargeSummaryService.class);
    private static final DateTimeFormatter FMT = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

    private final HikariDataSource dataSource;

    public DischargeSummaryService(HikariDataSource dataSource) {
        this.dataSource = dataSource;
    }

    public DischargeSummaryService() {
        this.dataSource = null;
    }

    /**
     * Builds a formatted discharge summary string for the given patient.
     * Uses in-memory history if DB is unavailable.
     */
    public String generateSummary(PatientRecord record, String assignedDoctor, String bedId) {
        StringBuilder sb = new StringBuilder();
        sb.append("╔══════════════════════════════════════════════════════╗\n");
        sb.append("║         VITA-SYNC — PATIENT DISCHARGE SUMMARY        ║\n");
        sb.append("╚══════════════════════════════════════════════════════╝\n\n");

        sb.append(String.format("  Patient ID   : %s\n", record.getPatientId()));
        sb.append(String.format("  Name         : %s\n", record.getName()));
        sb.append(String.format("  Age          : %d years\n", record.getAge()));
        sb.append(String.format("  Assigned Bed : %s\n", bedId != null ? bedId : "—"));
        sb.append(String.format("  Doctor       : %s\n", assignedDoctor != null ? assignedDoctor : "Not assigned"));
        sb.append(String.format("  Discharge At : %s\n\n", LocalDateTime.now().format(FMT)));

        // Try DB first, fall back to in-memory history
        if (dataSource != null) {
            appendDbStats(sb, record.getPatientId());
        } else {
            appendInMemoryStats(sb, record);
        }

        sb.append("\n  ─────────────────────────────────────────────────────\n");
        sb.append("  Status: DISCHARGED ✔\n");
        sb.append("  Generated by VITA-SYNC Integrated Monitoring System\n");
        return sb.toString();
    }

    private void appendDbStats(StringBuilder sb, String patientId) {
        String sql = "SELECT " +
                     "  COUNT(*)                                    AS total_readings, " +
                     "  ROUND(AVG(heart_rate), 1)                  AS avg_hr, " +
                     "  ROUND(AVG(spo2), 1)                        AS avg_spo2, " +
                     "  MIN(heart_rate)                             AS min_hr, " +
                     "  MAX(heart_rate)                             AS max_hr, " +
                     "  MIN(spo2)                                   AS min_spo2, " +
                     "  SUM(CASE WHEN heart_rate < 40 OR heart_rate > 140 OR spo2 < 90 THEN 1 ELSE 0 END) AS critical_events, " +
                     "  MIN(recorded_at)                            AS admitted_at, " +
                     "  MAX(recorded_at)                            AS last_reading " +
                     "FROM vital_sign_history WHERE patient_id = ?";
        try (Connection conn = dataSource.getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, patientId);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    sb.append("  ── Vital Sign Statistics (from Database) ──\n\n");
                    sb.append(String.format("  Total Readings   : %d\n",   rs.getInt("total_readings")));
                    sb.append(String.format("  Avg Heart Rate   : %.1f bpm\n", rs.getDouble("avg_hr")));
                    sb.append(String.format("  HR Range         : %d – %d bpm\n", rs.getInt("min_hr"), rs.getInt("max_hr")));
                    sb.append(String.format("  Avg SpO2         : %.1f%%\n",  rs.getDouble("avg_spo2")));
                    sb.append(String.format("  Min SpO2         : %d%%\n",    rs.getInt("min_spo2")));
                    sb.append(String.format("  Critical Events  : %d\n",      rs.getInt("critical_events")));
                    Timestamp admitted = rs.getTimestamp("admitted_at");
                    Timestamp last     = rs.getTimestamp("last_reading");
                    if (admitted != null) sb.append(String.format("  Admitted At      : %s\n", admitted.toLocalDateTime().format(FMT)));
                    if (last     != null) sb.append(String.format("  Last Reading     : %s\n", last.toLocalDateTime().format(FMT)));
                }
            }
        } catch (SQLException e) {
            log.warn("Could not fetch DB stats for discharge summary: {}", e.getMessage());
            sb.append("  (DB stats unavailable — showing current vitals only)\n");
        }
    }

    private void appendInMemoryStats(StringBuilder sb, PatientRecord record) {
        List<VitalSignReading> history = record.getHistory();
        sb.append("  ── Vital Sign Statistics (In-Memory) ──\n\n");
        if (history.isEmpty()) {
            sb.append("  No readings recorded.\n");
            return;
        }
        double avgHr   = history.stream().mapToInt(VitalSignReading::getHeartRate).average().orElse(0);
        double avgSpo2 = history.stream().mapToInt(VitalSignReading::getSpO2).average().orElse(0);
        int    minHr   = history.stream().mapToInt(VitalSignReading::getHeartRate).min().orElse(0);
        int    maxHr   = history.stream().mapToInt(VitalSignReading::getHeartRate).max().orElse(0);
        int    minSpo2 = history.stream().mapToInt(VitalSignReading::getSpO2).min().orElse(0);
        long   critical = history.stream()
                .filter(r -> r.getHeartRate() < 40 || r.getHeartRate() > 140 || r.getSpO2() < 90)
                .count();

        sb.append(String.format("  Total Readings   : %d\n",   history.size()));
        sb.append(String.format("  Avg Heart Rate   : %.1f bpm\n", avgHr));
        sb.append(String.format("  HR Range         : %d – %d bpm\n", minHr, maxHr));
        sb.append(String.format("  Avg SpO2         : %.1f%%\n",  avgSpo2));
        sb.append(String.format("  Min SpO2         : %d%%\n",    minSpo2));
        sb.append(String.format("  Critical Events  : %d\n",      critical));
    }
}
